management:
  endpoints: 
    web.exposure.include: '*'
  endpoint:
    health.show-details: always

spring:
  application.name: gnanamtesting
  output.ansi.enabled: always
  cloud.config:
    enabled: true
    server: 
      git:
        uri: 'file:///home/vagrant/workspace/{application}'
        timeout: 90
        searchPaths: config,conf
      health:
        repositories:
          gnanamtesting:
            lable: master
            name: gnanamtesting
            profiles: default
server.port: 8888
